plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fanter.keyboard'
    compileSdk 34

    defaultConfig {
        applicationId "com.fanter.keyboard"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {}
